"""
Chat API - Supports JSON response and SSE streaming response
"""

import json
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from app.core.logger import logger
from app.models.schemas import ChatRequest, ChatResponse, CitationsResponse
from app.services.graph_rag_service import get_graph_rag_service

router = APIRouter(prefix="/v1/chat", tags=["Chat"])


@router.post(
    "/completions",
    response_model=ChatResponse,
    summary="Graph RAG Chat (JSON)",
    description=(
        "Intelligent Q&A based on Graph RAG."
        "Retrieval pipeline: Query vectorization → Milvus Top-K → Neo4j subgraph → LLM answer generation"
    ),
)
async def chat_completions(request: ChatRequest):
    """
    Standard JSON-format Graph RAG chat

    - Vectorize the user query
    - Retrieve Top-K similar text chunks from Milvus
    - Query related entities and subgraph relations from Neo4j
    - Fuse context and generate answer via LLM
    """
    try:
        graph_rag = get_graph_rag_service()
        response = await graph_rag.chat(
            query=request.query,
            top_k=request.top_k,
            chat_id=request.chat_id,
        )
        return response
    except RuntimeError as e:
        logger.error("Chat service error: %s", str(e))
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        logger.error("Chat request failed: %s", str(e), exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Chat request failed: {str(e)}",
        )


@router.post(
    "/stream",
    summary="Graph RAG Chat (SSE Streaming)",
    description=(
        "Streaming intelligent Q&A based on Graph RAG."
        "Uses Server-Sent Events (SSE) to progressively return text generated by the LLM."
    ),
)
async def chat_stream(request: ChatRequest):
    """
    SSE streaming Graph RAG chat

    - Returns Content-Type: text/event-stream
    - Each SSE data field contains a JSON-encoded StreamChunk
    - Sends finished: true when the stream ends
    """
    async def event_generator():
        try:
            graph_rag = get_graph_rag_service()
            async for chunk in graph_rag.chat_stream(
                query=request.query,
                top_k=request.top_k,
                chat_id=request.chat_id,
            ):
                # SSE format: data: {json}\n\n
                chunk_json = chunk.model_dump_json()
                yield f"data: {chunk_json}\n\n"
        except RuntimeError as e:
            logger.error("Streaming chat service error: %s", str(e))
            error_data = json.dumps({"error": str(e)})
            yield f"data: {error_data}\n\n"
        except Exception as e:
            logger.error("Streaming chat failed: %s", str(e), exc_info=True)
            error_data = json.dumps({"error": f"Streaming chat failed: {str(e)}"})
            yield f"data: {error_data}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get(
    "/citations/{chat_id}",
    response_model=CitationsResponse,
    summary="Get Citation Text Blocks",
    description="Displays the specific text block indices, similarity scores, and corresponding original content cited by the LLM in a conversation",
)
async def get_citations(chat_id: str):
    """
    Get citation text blocks for a specific chat

    - Returns chunk_id, similarity score, and original content of each citation
    """
    graph_rag = get_graph_rag_service()
    result = graph_rag.get_citations(chat_id)

    if result is None:
        raise HTTPException(
            status_code=404,
            detail=f"Citation info not found for chat_id={chat_id}",
        )

    return result